## Site info:
title: SurfingDL
tagline: Wonik's Machine & Deep Learning Blog
author: Wonik Jang
email: jwimsms@gmail.com
description: "Deep Learning" 
keywords: "Wonik's Machine & Deep Learning Blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wonikjang.github.io" # the base hostname & protocol for your site
locale: en_us

### Personal info and site tools info:
github_username:  wonikjang
disqus_shortname: wonikjang-github-io
favicon:     "/images/favicon.ico"
aboutme: Surfing into Deep Learning & Machine Learning on the board of Big Data
aboutme_photo: "/images/surfing.jpg"
#google_analytics_key:  UA-93680824-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr), Russian (ru), and Turkish (tr)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"
  
    kr:
      Aboutme: "저자 소개"
      Archives: "모든 게시물"
      Blogroll: "참조 링크"
      Categories: "카테고리"
      Copyright_Notice: "저작권"
      Recent_Posts: "최근 게시물"
      Tags: "태그"
      Previous: "이전 게시물"
      Next: "다음 게시물"
      PostedInCategories: "카테고리: "
      Taggedwith: "태그: "
      PostDate: "작성일: "
      Google_search: "게시물 검색"
      Home: "홈"
      About: "소개"
      Guestbook: "방명록"
      Subscribe: "구독하기"
   

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Freshman
        href: http://yulijia.net/freshman
        title: Another Jekyll blog theme
      - name: author's website
        href: http://yulijia.net/
        title: Lijia Yu's website


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
- jekyll-seo-tag
paginate: 5
excerpt_separator: <!-- more -->
